#This is the external configuration file for various environments - DEV, PROD, etc.
---
logging:
  root: DEBUG
  org.springframework: DEBUG
  com.exl.rdaas: DEBUG
  file:
    name: logs/Api.log
  pattern:
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level  - %msg%n'
  logback:
    rollingpolicy:
      file-name-pattern: 'logs/Api.%d{yyyy-MM-dd}.%i.log'
      max-file-size: 10MB
      max-history: 60
spring:
  http:
    encoding:
      force: 'false'
  config:
    activate:
      on-profile: default
  application:
    name: RDaas
  output:
    ansi:
     enabled: always
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    username: sa
    url: jdbc:h2:~/rdaasdb
    driverClassName: org.h2.Driver
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: 'true'
    hibernate:
      ddl-auto: update
rdaas:
  app:
    jwtExpirationMs: '86400000'
    jwtCookieName: rdaas
    jwtSecret: secreykey
     
server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: false
---
spring:
  config:
    activate:
      on-profile: dev
  application:
    name: RDaas-dev
  output:
    ansi:
     enabled: always
server:
  port: 8082

connector:
  -
    name: Socure    
  -
    name: Experian   